// Schema evolution corpus for the Nexus event encoder.
//
// Ch05 teaches that Protobuf compatibility rules are not vague
// guidelines — they're enforceable invariants over the wire format.
// This file pins those invariants down with byte-level golden
// vectors so a future refactor that breaks compatibility fails
// loudly here rather than silently in production.
//
// Tests come in four shapes:
//
//   1. Golden stability — Marshal(canonical) MUST produce a known
//      hex string. If the encoder changes the wire format (field
//      ordering, varint encoding, etc.) this test catches it
//      immediately. Reviewers can verify the change is intentional
//      and update the golden in the same commit.
//
//   2. Forward compatibility — a v1 decoder MUST read v2 bytes
//      successfully, ignoring fields it doesn't know about. This
//      is what makes rolling deployments safe: a new producer can
//      add fields without breaking old consumers in the field.
//
//   3. Backward compatibility — a v2-aware decoder MUST read v1
//      bytes successfully, defaulting missing fields to zero.
//      This is what makes upgrades reversible: a new consumer
//      can still process the backlog of pre-upgrade messages.
//
//   4. Negative cases — a BREAKING change (renumbered field) MUST
//      lose data when decoded by a v1 reader. This isn't really
//      a regression test — it's a *demonstration* of why field
//      numbers are immutable contract elements, not just labels.
//
// White-box (package protobuf, not protobuf_test) because the v2
// corpus is constructed by calling the unexported append* helpers.
// In real code, v2 would use generated protoc output; the educational
// version reuses the v1 primitives to keep the wire format visible.

package protobuf

import (
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"testing"
	"time"

	"github.com/mohgh/nexus/internal/domain"
)

// canonicalEvent returns the deterministic input used by every test
// in this file. Values are deliberately NON-trivial:
//
//   - Value = 1.5 has a distinctive little-endian byte pattern
//     (00 00 00 00 00 00 F8 3F). A regression flipping the encoder
//     to big-endian would produce 3F F8 .. instead, failing the
//     golden. A zero-valued canonical event couldn't catch this
//     since 0.0 looks identical in either endianness.
//
//   - OccurredAt = Unix(1, 0) → UnixNano = 1e9, which varint-
//     encodes as 5 bytes (80 94 eb dc 03). This exercises the
//     multi-byte varint path; a single-zero-byte encoding
//     (Unix(0,0)) would not catch a regression in the varint
//     loop.
//
// Strings stay short ASCII so the hex golden remains human-skimmable.
func canonicalEvent() *domain.Event {
	return &domain.Event{
		ID:         "id1",
		TenantID:   "t1",
		EventType:  "view",
		Payload:    json.RawMessage(`{}`),
		Value:      1.5,
		OccurredAt: time.Unix(1, 0).UTC(),
	}
}

// v1Golden is the byte-exact encoding canonicalEvent() must produce
// under v1 Marshal. Decoded as hex for readability — each two-char
// pair is one byte. Layout, byte by byte:
//
//	0a 03 69 64 31              field 1 (id),         length 3, "id1"
//	12 02 74 31                 field 2 (tenant_id),  length 2, "t1"
//	1a 04 76 69 65 77           field 3 (event_type), length 4, "view"
//	22 02 7b 7d                 field 4 (payload),    length 2, "{}"
//	29 00 00 00 00 00 00 f8 3f  field 5 (value),      8 bytes,  1.5 little-endian
//	30 80 94 eb dc 03           field 6 (occurred_at), 5-byte varint of 1e9
const v1Golden = "0a0369643112027431" +
	"1a047669657722027b7d" +
	"29000000000000f83f" +
	"308094ebdc03"

// TestGolden_V1MarshalProducesExactBytes pins the wire format. If
// this test ever fails, the encoder has changed in a way producers
// and consumers on different deploy generations will disagree about.
func TestGolden_V1MarshalProducesExactBytes(t *testing.T) {
	got, err := Marshal(canonicalEvent())
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}
	gotHex := hex.EncodeToString(got)
	if gotHex != v1Golden {
		t.Fatalf("wire format changed:\n  got:  %s\n  want: %s", gotHex, v1Golden)
	}
}

// eventV2 is the test-only v2 schema: v1's fields plus two
// optional strings. In production code v2 would be generated by
// protoc; here we model it as a plain struct embedding the v1
// event so the test reads naturally.
type eventV2 struct {
	domain.Event
	Source  string // field 7
	TraceID string // field 8
}

// marshalV2 is the "v2 producer" used by the compatibility tests.
// It writes fields 1-6 (identical to v1) plus two new optional
// fields:
//
//	7 = source    (string)  — provenance label, e.g. "web", "mobile"
//	8 = trace_id  (string)  — distributed-tracing correlation ID
//
// These tags (7, 8) are unused in v1, so a v1 decoder must ignore
// them. Field numbers are never reused — adding fields is always
// done by allocating a new tag.
func marshalV2(v2 *eventV2) []byte {
	b, _ := Marshal(&v2.Event)
	b = appendString(b, 7, v2.Source)
	b = appendString(b, 8, v2.TraceID)
	return b
}

// unmarshalV2 is the "v2 consumer" used by the backward-compat
// test. It decodes the v1 fields via the production Unmarshal,
// then walks the message a second time pulling out tags 7 and 8
// if present. Missing v2 fields default to zero values — that's
// what makes v2 consumers backward-compatible with v1 producers.
//
// The walk-twice approach keeps the production Unmarshal entirely
// untouched (it has no knowledge of v2), which is realistic: in a
// generated-code world, you'd run the v1 decoder then the v2
// decoder against the same buffer, or use a single generated
// decoder that knows both.
func unmarshalV2(data []byte, v2 *eventV2) error {
	if err := Unmarshal(data, &v2.Event); err != nil {
		return err
	}
	// Second pass for v2-only fields. We tolerate the same wire
	// types the production decoder handles plus skip the rest, so
	// this stays robust if the producer mixes in v3 fields too.
	cur := data
	for len(cur) > 0 {
		fieldNum, wireType, n, err := readTag(cur)
		if err != nil {
			return err
		}
		cur = cur[n:]
		switch wireType {
		case 0: // varint
			_, n := binary.Uvarint(cur)
			cur = cur[n:]
		case 1: // 64-bit fixed
			cur = cur[8:]
		case 2: // length-delimited
			length, n := binary.Uvarint(cur)
			cur = cur[n:]
			val := cur[:length]
			switch fieldNum {
			case 7:
				v2.Source = string(val)
			case 8:
				v2.TraceID = string(val)
			}
			cur = cur[length:]
		case 5: // 32-bit fixed
			cur = cur[4:]
		}
	}
	return nil
}

// TestForwardCompat_V1DecoderReadsV2Bytes is the headline
// compatibility test: a v1-vintage decoder receives bytes from a
// v2-vintage producer and must successfully extract every v1 field
// without erroring on the unknown trailing fields.
func TestForwardCompat_V1DecoderReadsV2Bytes(t *testing.T) {
	original := canonicalEvent()
	v2Bytes := marshalV2(&eventV2{
		Event:   *original,
		Source:  "web",
		TraceID: "trace-abc-123",
	})

	decoded := &domain.Event{}
	if err := Unmarshal(v2Bytes, decoded); err != nil {
		t.Fatalf("v1 decoder rejected v2 bytes — forward compat is broken: %v", err)
	}

	// EVERY v1 field must round-trip — not just the strings.
	// Checking all six guards against a regression that only
	// preserves some fields in the presence of trailing v2 data.
	if decoded.ID != original.ID {
		t.Fatalf("ID lost: got %q, want %q", decoded.ID, original.ID)
	}
	if decoded.TenantID != original.TenantID {
		t.Fatalf("TenantID lost: got %q, want %q", decoded.TenantID, original.TenantID)
	}
	if decoded.EventType != original.EventType {
		t.Fatalf("EventType lost: got %q, want %q", decoded.EventType, original.EventType)
	}
	if string(decoded.Payload) != string(original.Payload) {
		t.Fatalf("Payload lost: got %s, want %s", decoded.Payload, original.Payload)
	}
	if decoded.Value != original.Value {
		t.Fatalf("Value lost: got %f, want %f", decoded.Value, original.Value)
	}
	if !decoded.OccurredAt.Equal(original.OccurredAt) {
		t.Fatalf("OccurredAt lost: got %v, want %v", decoded.OccurredAt, original.OccurredAt)
	}
}

// TestForwardCompat_V1DecoderSkipsWireType5 guards the bug the
// audit caught: an earlier version of Unmarshal errored on any
// wire type it didn't recognise. Real proto3 producers emit wire
// type 5 (32-bit fixed) for float and fixed32 fields, so a future
// schema adding `float32 confidence_score = 9` would have broken
// every v1 consumer in production. The decoder must skip the 4
// bytes cleanly.
func TestForwardCompat_V1DecoderSkipsWireType5(t *testing.T) {
	b, _ := Marshal(canonicalEvent())
	// Append field 9 with wire type 5 (32-bit fixed): tag byte is
	// (9 << 3) | 5 = 0x4d. Payload: 4 bytes of an IEEE-754 float32
	// 1.0 little-endian.
	b = append(b, 0x4d, 0x00, 0x00, 0x80, 0x3f)

	decoded := &domain.Event{}
	if err := Unmarshal(b, decoded); err != nil {
		t.Fatalf("wire-type-5 forward compat broken: %v", err)
	}
	if decoded.ID != "id1" {
		t.Fatalf("v1 field lost when wire-type-5 followed: ID=%q", decoded.ID)
	}
}

// TestBackwardCompat_V2DecoderReadsV1Bytes models the upgrade
// direction: a v2-aware consumer (unmarshalV2 + eventV2 struct)
// reads bytes from a v1-vintage producer. v2's extra fields
// (source, trace_id) are absent from the wire — the v2 reader
// must accept that, defaulting them to zero, NOT erroring.
//
// This test was previously a tautology — it just called the
// production Unmarshal on v1 bytes, which is what
// TestMarshalUnmarshal_RoundTrip already did. Now eventV2 +
// unmarshalV2 give us a real v2 decoder distinct from v1, so
// "v2 reads v1" is a non-trivial assertion.
func TestBackwardCompat_V2DecoderReadsV1Bytes(t *testing.T) {
	original := canonicalEvent()
	v1Bytes, _ := Marshal(original)

	decoded := &eventV2{}
	if err := unmarshalV2(v1Bytes, decoded); err != nil {
		t.Fatalf("v2 decoder rejected v1 bytes: %v", err)
	}

	// v1 fields populated normally.
	if decoded.ID != original.ID {
		t.Fatalf("v1 field lost: ID=%q want %q", decoded.ID, original.ID)
	}
	// v2-only fields default to zero — THIS is the backward-compat
	// property. A producer that doesn't know about Source/TraceID
	// can still talk to a consumer that does.
	if decoded.Source != "" {
		t.Fatalf("Source should default to zero in absence of field 7, got %q", decoded.Source)
	}
	if decoded.TraceID != "" {
		t.Fatalf("TraceID should default to zero in absence of field 8, got %q", decoded.TraceID)
	}
}

// TestRoundTrip_V2Bytes pins the v2 path end-to-end: marshalV2
// followed by unmarshalV2 must round-trip BOTH the v1 fields AND
// the new v2-only fields. Without this, "v2 producer" and
// "v2 consumer" could drift in opposite directions on the same
// tag and the forward/backward tests above wouldn't catch it.
func TestRoundTrip_V2Bytes(t *testing.T) {
	original := &eventV2{
		Event:   *canonicalEvent(),
		Source:  "mobile",
		TraceID: "trace-xyz-789",
	}
	b := marshalV2(original)

	decoded := &eventV2{}
	if err := unmarshalV2(b, decoded); err != nil {
		t.Fatalf("v2 round-trip failed: %v", err)
	}
	if decoded.Source != original.Source {
		t.Fatalf("Source: got %q want %q", decoded.Source, original.Source)
	}
	if decoded.TraceID != original.TraceID {
		t.Fatalf("TraceID: got %q want %q", decoded.TraceID, original.TraceID)
	}
}

// TestBreakingChange_RenumberingLosesData demonstrates WHY field
// numbers are an immutable contract: if a developer "renames"
// field 1 to field 99 thinking it's a cosmetic change, every
// existing consumer silently loses the data. This isn't a bug
// to fix — it's the lesson. The test pins the failure mode so
// it can't be misconstrued as a transient decoder issue.
//
// Bytes are built field-by-field via the encoder helpers rather
// than by slicing Marshal's output, so this test stays robust
// against any future changes to v1 field ordering. The Golden
// test handles encoding-stability; this test handles the
// semantics of renumbering specifically.
func TestBreakingChange_RenumberingLosesData(t *testing.T) {
	original := canonicalEvent()

	// Build bytes that LOOK like a canonical event but with ID
	// emitted under tag 99 instead of tag 1. All other fields
	// keep their original tags so we can prove the bug is
	// localized to the renumbered field, not a wholesale parse
	// failure.
	var b []byte
	b = appendString(b, 99, original.ID) // field 1 renumbered to 99
	b = appendString(b, 2, original.TenantID)
	b = appendString(b, 3, original.EventType)
	b = appendBytes(b, 4, []byte(original.Payload))
	b = appendFloat64(b, 5, original.Value)
	b = appendInt64(b, 6, original.OccurredAt.UnixNano())

	decoded := &domain.Event{}
	if err := Unmarshal(b, decoded); err != nil {
		t.Fatalf("renumbered-field message failed to parse at all: %v", err)
	}
	// THIS is the breaking change: ID is empty because the v1
	// decoder only looks at field number 1, and the data is under
	// field 99 now.
	if decoded.ID != "" {
		t.Fatalf("expected v1 decoder to lose ID after renumber, got %q", decoded.ID)
	}
	// Other fields are intact because their tags are unchanged —
	// the breakage is precisely scoped to the field that moved.
	if decoded.TenantID != original.TenantID {
		t.Fatalf("non-renumbered fields should still decode: tenant_id=%q", decoded.TenantID)
	}
	if decoded.EventType != original.EventType {
		t.Fatalf("non-renumbered fields should still decode: event_type=%q", decoded.EventType)
	}
}

// TestUnmarshal_TruncatedLengthFails is a negative-case guard: if
// a length-delimited field claims more bytes than the message has,
// the decoder must surface the error rather than read past the end
// of the buffer. The Ch05 lesson is that Protobuf compactness has
// a cost — there's no end-of-message marker, so the decoder
// implicitly trusts the length prefix.
func TestUnmarshal_TruncatedLengthFails(t *testing.T) {
	// Field 1 (ID), wire type 2, length 100 — but only 3 bytes
	// follow. A correct decoder must reject this.
	b := []byte{0x0a, 0x64, 'i', 'd', '1'}

	decoded := &domain.Event{}
	if err := Unmarshal(b, decoded); err == nil {
		t.Fatalf("expected error on truncated length, got nil")
	}
}
