// Package eventstore implements an append-only event store for CQRS.
//
// Ch13 teaching points:
//  1. Event sourcing: instead of storing current state, store the sequence
//     of state changes (events). Current state is derived by replaying events.
//  2. The event store is append-only — events are never updated or deleted.
//     This gives you a full audit trail and time-travel queries for free.
//  3. CQRS (Command Query Responsibility Segregation): writes go to the
//     event store (command side), reads come from denormalized projections
//     (query side). The projection is rebuilt from the event log.
//  4. The event store table uses a sequence number (stream_position) that is
//     globally ordered. Projections track the last position they've processed
//     to know where to resume after a restart.
//
// DDIA reference: Chapter 11 — "Event Sourcing" and "Change Data Capture."
package eventstore

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

// StoredEvent is one entry in the append-only event log.
type StoredEvent struct {
	StreamPosition int64           `json:"stream_position"` // global sequence number
	StreamName     string          `json:"stream_name"`     // e.g. "tenant-{id}" or "billing-{id}"
	EventType      string          `json:"event_type"`      // e.g. "TenantCreated", "EventIngested"
	Data           json.RawMessage `json:"data"`            // event payload
	Metadata       json.RawMessage `json:"metadata"`        // correlation ID, actor, etc.
	OccurredAt     time.Time       `json:"occurred_at"`
}

// Store is an append-only event store backed by PostgreSQL.
type Store struct {
	pool *pgxpool.Pool
}

// NewStore creates an event store using the given PostgreSQL pool.
// The events_store table must exist (see migration 004).
func NewStore(pool *pgxpool.Pool) *Store {
	return &Store{pool: pool}
}

// Append writes one or more events to the store atomically.
// All events in a single call get consecutive stream_positions.
//
// Ch13: notice there is no UPDATE — only INSERT. This is the core
// invariant of event sourcing. The stream_position is generated by
// a PostgreSQL BIGSERIAL, guaranteeing global ordering.
func (s *Store) Append(ctx context.Context, events ...StoredEvent) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("eventstore: begin tx: %w", err)
	}
	defer tx.Rollback(ctx) //nolint:errcheck

	for _, e := range events {
		_, err := tx.Exec(ctx,
			`INSERT INTO events_store (stream_name, event_type, data, metadata, occurred_at)
			 VALUES ($1, $2, $3, $4, $5)`,
			e.StreamName, e.EventType, []byte(e.Data), []byte(e.Metadata), e.OccurredAt,
		)
		if err != nil {
			return fmt.Errorf("eventstore: insert: %w", err)
		}
	}

	return tx.Commit(ctx)
}

// ReadStream returns all events for a given stream name, ordered by position.
// This is how you rebuild the state of an aggregate: replay all its events.
func (s *Store) ReadStream(ctx context.Context, streamName string) ([]StoredEvent, error) {
	rows, err := s.pool.Query(ctx,
		`SELECT stream_position, stream_name, event_type, data, metadata, occurred_at
		 FROM events_store
		 WHERE stream_name = $1
		 ORDER BY stream_position`,
		streamName,
	)
	if err != nil {
		return nil, fmt.Errorf("eventstore: read stream: %w", err)
	}
	defer rows.Close()
	return scanStoredEvents(rows)
}

// HeadPosition returns the highest stream_position written, or 0
// if the event store is empty. Used by the projection runner to
// report lag (head - last_applied).
func (s *Store) HeadPosition(ctx context.Context) (int64, error) {
	var head int64
	err := s.pool.QueryRow(ctx,
		`SELECT COALESCE(MAX(stream_position), 0) FROM events_store`,
	).Scan(&head)
	if err != nil {
		return 0, fmt.Errorf("eventstore: head: %w", err)
	}
	return head, nil
}

// ReadAllFrom returns events from all streams starting after the given position.
// Projections use this to catch up: "give me everything after position X."
//
// Limit prevents unbounded reads during catch-up of a large backlog.
func (s *Store) ReadAllFrom(ctx context.Context, afterPosition int64, limit int) ([]StoredEvent, error) {
	if limit <= 0 || limit > 10000 {
		limit = 1000
	}
	rows, err := s.pool.Query(ctx,
		`SELECT stream_position, stream_name, event_type, data, metadata, occurred_at
		 FROM events_store
		 WHERE stream_position > $1
		 ORDER BY stream_position
		 LIMIT $2`,
		afterPosition, limit,
	)
	if err != nil {
		return nil, fmt.Errorf("eventstore: read all from %d: %w", afterPosition, err)
	}
	defer rows.Close()
	return scanStoredEvents(rows)
}

func scanStoredEvents(rows interface {
	Next() bool
	Scan(dest ...any) error
	Err() error
}) ([]StoredEvent, error) {
	var out []StoredEvent
	for rows.Next() {
		var e StoredEvent
		var data, meta []byte
		if err := rows.Scan(&e.StreamPosition, &e.StreamName, &e.EventType, &data, &meta, &e.OccurredAt); err != nil {
			return nil, fmt.Errorf("eventstore: scan: %w", err)
		}
		e.Data = json.RawMessage(data)
		e.Metadata = json.RawMessage(meta)
		out = append(out, e)
	}
	return out, rows.Err()
}
